"""Adding currently_live_in field

Revision ID: 1b4661c2aaa8
Revises: None
Create Date: 2013-11-30 08:39:12.608334

"""

# revision identifiers, used by Alembic.
revision = '1b4661c2aaa8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currently_live_in', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currently_live_in')
    ### end Alembic commands ###
