"""Adding currently_live_in field

Revision ID: 5145ac2c72c4
Revises: None
Create Date: 2013-12-01 08:55:53.588715

"""

# revision identifiers, used by Alembic.
revision = '5145ac2c72c4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('portfolio_title_key', 'portfolio')
    op.add_column('users', sa.Column('currently_live_in', sa.String(length=300), nullable=True))
    op.drop_index('users_username_key', 'users')
    op.drop_index('users_email_key', 'users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('users_email_key', 'users', [u'email'], unique=True)
    op.create_index('users_username_key', 'users', [u'username'], unique=True)
    op.drop_column('users', 'currently_live_in')
    op.create_index('portfolio_title_key', 'portfolio', [u'title'], unique=True)
    ### end Alembic commands ###
