#!/usr/bin/python
import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from main import *
db.drop_all()
db.create_all()
db.session.add(Users(username='ekowibowo', firstname='Eko', lastname='Suprapto Wibowo', password='rahasia', email='swdev.bali@gmail.com', tagline='A cool coder and an even cooler Capoeirista', bio = 'Amazingly created creature', avatar = '/static/avatar.png'))
db.session.commit()
